name: Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main, dev ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install conan
        run: pip install conan

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}\build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}

      - name: Move program and binary
        run: |
          mkdir ${{github.workspace}}\build\program
          copy ${{github.workspace}}\build\src\Release\Main.exe ${{github.workspace}}\build\program
          copy ${{github.workspace}}\build\conan\bin\fmt.dll ${{github.workspace}}\build\program
          copy ${{github.workspace}}\build\conan\bin\spdlog.dll ${{github.workspace}}\build\program

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: gtproxy-${{github.sha}}
          path: ${{github.workspace}}\build\program