name: CI

on:
  pull_request:
  push:
    branches: [ dev ]

jobs:
  dev:
    runs-on: windows-2022
    env:
      BUILD_TYPE: DEBUG

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install conan
        run: pip install conan

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}\build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGTPROXY_BUILD_VERSION=${{github.run_number}}

      - name: Build
        run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}

      - name: Move program and binary
        run: |
          mkdir ${{github.workspace}}\build\program
          copy ${{github.workspace}}\build\src\${{env.BUILD_TYPE}}\*.exe ${{github.workspace}}\build\program
          copy ${{github.workspace}}\build\conan\bin\*.dll ${{github.workspace}}\build\program
          copy ${{github.workspace}}\build\vendor\enet\${{env.BUILD_TYPE}}\*.dll ${{github.workspace}}\build\program

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: gtproxy-${{github.sha}}
          path: ${{github.workspace}}\build\program
